name: Jacob Conrad's Website
title: Jacob Conrad
plugins:
  - jemoji
remote_theme: "dracula/gh-pages"
colorspace: [purple]
description: [Welcome to my website! This website helps you learn more about me and take a look at the programming work I have done so far.]
